### ISSUE TITLE
peError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by sayem314** [fent/node-m3u8stream#63]
```
at new ClientRequest (_http_client.js:148:13)
at request (https.js:314:10)
at Object.get (https.js:318:15)
at doDownload (...node_modules/miniget/dist/index.js:110:25)
at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

m3u8 url: https://cf-hls-media.sndcdn.com/playlist/8IsFZS7TMDjy.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0LzhJc0ZaUzdUTURqeS4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1ODcwNTE3MjJ9fX1dfQ__&Signature=af4QA-bocT7jB6bsI~3ZbcSYx~jWpxkUKDDcPD--6iY7XjaDzTV6aTOPi5N2SyTtwaMgpNDJ1U6~HfGPducyQdkOWPyVd~1obDj7RG~AoendyxOaFpTxmUyBxvfw~GIUOT8Z~KlNx-OfUvLOWdZXlXlZMDYOxH18AEscqCKUImSaG6WLQA123byNBQwpwogR8qxNt41DbcM2KlyYz9TQRIRH2BRNK0gP~zEXzFez3NFxlJJ8Z5ZProEjze9bhmjpxmnAMDgrYCfWin2QVZBGpwFDXahqtZZ6glAeqLwlWixh6-Ovej73iwH7FhCfwD85cNm3GZZ78nCr4H~~fd2SPg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ

**Comment by fent** [comment]
I think this simply requires a `decodeURIComponent` call. can you post the file here, or part of it? I can't access it with the above link

**Comment by sayem314** [comment]
@fent here is the m3u8 content

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:1.985272,
https://cf-hls-media.sndcdn.com/media/0/31762/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:2.977908,
https://cf-hls-media.sndcdn.com/media/31763/79410/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:4.989302,
https://cf-hls-media.sndcdn.com/media/79411/159240/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/159241/318900/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/318901/478561/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/478562/638221/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/638222/797882/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/797883/957542/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/957543/1117202/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1117203/1276863/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1276864/1436523/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1436524/1596184/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1596185/1755844/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1755845/1915505/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/1915506/2075165/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/2075166/2234825/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/2234826/2394486/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/2394487/2554146/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/2554147/2713807/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:9.978604,
https://cf-hls-media.sndcdn.com/media/2713808/2873467/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXTINF:7.418648,
https://cf-hls-media.sndcdn.com/media/2873468/2992167/8IsFZS7TMDjy.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL21lZGlhLyovKi84SXNGWlM3VE1EankuMTI4Lm1wMyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU4ODIyNjg1N319fV19&Signature=Kl17Dq7cGEGfaimAam1zT3wQ2lbk-wfI6HekqUNOfjIRBWr0ipu26v4oyL41YFO7n1wbb8pPJaIRnMLF0JytsrrWs1GalG7dU3VPn2608Sxdg0kH4HjxZzSrP87xtAsI6PXZjCbYD0XQS3Q83y0kvwc~dIhHLzSmt2wC1rc8nlFZPYK8RnYlolWjCUYEgxXwY8OmafxJ~OBYelYwEzOFQa3VSHtDvAIjJ~0qCI51eAqxNcIOX97Jmn2nDHCiwpyAnLrntSdXin5Lg2vNY9AsEX-4K652Nq58k~J-gCIkPzp9W-07uUxKUEsdKCI5zAfZEt6RpXpLRqjKdwddPP7kPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ
#EXT-X-ENDLIST
```

**Comment by sayem314** [comment]
Just tested again with `v0.7.0 ` and issue still exists even with `decodeURI`
