### ISSUE TITLE
Unhandled 'error' event when I reach 403 HTTP error code

### ISSUE THREAD

**Issue by alexroussel** [fent/node-m3u8stream#77]
Hello @fent,

I try to record a stream with m3u8 playlist file.
All is working fine but when the stream ends, the m3u8 reach a 403 HTTP error code (normal behaviour) then the app is crashing, btw the video is well written.
I'm looking for a way to handle when the 403 appears, without crashing the app, is a try catch or something else possible ?

The corresponding stack trace is below.
Thanks

```javascript
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Status code: 403
    at ClientRequest.<anonymous> (/node_modules/miniget/dist/index.js:147:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
Emitted 'error' event on PassThrough instance at:
    at PassThrough.onError (/node_modules/m3u8stream/dist/index.js:67:16)
    at PassThrough.emit (events.js:315:20)
    at ClientRequest.<anonymous> (/node_modules/miniget/dist/index.js:152:28)
    at Object.onceWrapper (events.js:422:26)
    [... lines matching original stack trace ...]
    at addChunk (_stream_readable.js:295:12)
```

**Comment by fent** [comment]
> All is working fine but when the stream ends, the m3u8 reach a 403 HTTP error code (normal behaviour)

normal behavior? is it expected for the server to return 403 after the stream ends?



> I'm looking for a way to handle when the 403 appears, without crashing the app, is a try catch or something else possible ?

listen for the `error` event, which is emitted on the `stream` returned from calling m3u8stream

```js
let stream = m3u8stream(url);
stream.on('error', err => {
  // error here
});
```

**Comment by alexroussel** [comment]
> normal behavior? is it expected for the server to return 403 after the stream ends?
Yes, it's expected ;)
> listen for the `error` event, which is emitted on the `stream` returned from calling m3u8stream
> 
> ```js
> let stream = m3u8stream(url);
> stream.on('error', err => {
>   // error here
> });
> ```

Thank you so much for the answer ! It's working perfect.
